# Generated by Django 3.0.6 on 2020-07-04 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20200421_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='slug',
            field=models.SlugField(default='default-post', max_length=200, unique=True),
        ),
    ]
